package com.example.mybatis.model;

import java.util.ArrayList;
import java.util.List;

public class Autori {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column autori.id
     *
     * @mbg.generated Mon Nov 06 15:27:41 CET 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column autori.nome_autore
     *
     * @mbg.generated Mon Nov 06 15:27:41 CET 2023
     */
    private String nomeAutore;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column autori.id
     *
     * @return the value of autori.id
     *
     * @mbg.generated Mon Nov 06 15:27:41 CET 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column autori.id
     *
     * @param id the value for autori.id
     *
     * @mbg.generated Mon Nov 06 15:27:41 CET 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column autori.nome_autore
     *
     * @return the value of autori.nome_autore
     *
     * @mbg.generated Mon Nov 06 15:27:41 CET 2023
     */
    public String getNomeAutore() {
        return nomeAutore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column autori.nome_autore
     *
     * @param nomeAutore the value for autori.nome_autore
     *
     * @mbg.generated Mon Nov 06 15:27:41 CET 2023
     */
    public void setNomeAutore(String nomeAutore) {
        this.nomeAutore = nomeAutore;
    }


    /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    // MY CODE                       ////////////////////////////////////////////////////////////////////////////////////
    /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//    List<Libri> libriAutore = new ArrayList<>();
//    public List<Libri> getLibriAutore() {
//        return libriAutore;
//    }
//    public void setLibriAutore(List<Libri> libriAutore) {
//        this.libriAutore = libriAutore;
//    }
//




}