package com.example.mybatis.mapper;


import com.example.mybatis.model.Autori;
import com.example.mybatis.model.AutoriExample;
import java.util.List;


import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
@Mapper
public interface AutoriMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table autori
     *
     * @mbg.generated Mon Nov 06 15:27:41 CET 2023
     */
    long countByExample(AutoriExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table autori
     *
     * @mbg.generated Mon Nov 06 15:27:41 CET 2023
     */
    int deleteByExample(AutoriExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table autori
     *
     * @mbg.generated Mon Nov 06 15:27:41 CET 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table autori
     *
     * @mbg.generated Mon Nov 06 15:27:41 CET 2023
     */
    int insert(Autori row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table autori
     *
     * @mbg.generated Mon Nov 06 15:27:41 CET 2023
     */
    int insertSelective(Autori row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table autori
     *
     * @mbg.generated Mon Nov 06 15:27:41 CET 2023
     */
    List<Autori> selectByExample(AutoriExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table autori
     *
     * @mbg.generated Mon Nov 06 15:27:41 CET 2023
     */
    Autori selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table autori
     *
     * @mbg.generated Mon Nov 06 15:27:41 CET 2023
     */
    int updateByExampleSelective(@Param("row") Autori row, @Param("example") AutoriExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table autori
     *
     * @mbg.generated Mon Nov 06 15:27:41 CET 2023
     */
    int updateByExample(@Param("row") Autori row, @Param("example") AutoriExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table autori
     *
     * @mbg.generated Mon Nov 06 15:27:41 CET 2023
     */
    int updateByPrimaryKeySelective(Autori row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table autori
     *
     * @mbg.generated Mon Nov 06 15:27:41 CET 2023
     */
    int updateByPrimaryKey(Autori row);


//////////////////////////////////////////MY CODE

//    List<Libri> selectAutoriWithLibri(Integer idM, Integer prezzol);
//
//
//    List<Autori> selectViaAutoriOrLibroOrCasa(Integer autoreID, Integer libroID, Integer casaID);
//
//
//
//    @Select({
//            "select",
//            "id, nome_autore",
//            "from autori",
//            "where id = #{id,jdbcType=INTEGER}"
//    })
//    @Results({
//            @Result(column="id", property="id", jdbcType= JdbcType.INTEGER, id=true),
//            @Result(column="nome_autore", property="nomeAutore", jdbcType=JdbcType.VARCHAR)
//    })
//    Autori selectByPrimaryKeyAnnotation(Integer id);



}